require("dotenv").config();
var express = require('express');
var router = express.Router();
var axios = require("axios");
var cloudinary = require("cloudinary");

const apiKey = process.env.CLOUDINARY_API_KEY;
const apiSecret = process.env.CLOUDINARY_API_SECRET;

router.post('/api/postImage', (req, res) => {
    postImage(req.body);
});

const CLOUDINARY_POST_URL=process.env.CLOUDINARY_POST_URL;

function postImage(body) {
    let data = body;
    // axios.post("https://api.cloudinary.com/v1_1/diegolealb/upload", data)
    //     .then(res => {
    //         console.log(res);
    //     })
    //     .catch(err => {
    //         console.error("ERROR", err.request);
    //     });

    var xhr = new XMLHttpRequest();
    var fd = new FormData();
    xhr.open('POST', "https://api.cloudinary.com/v1_1/diegolealb/upload", true);
    xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
};

function upload(file) {
    cloudinary.config({
        cloud_name: 'diegolealb',
        api_key: apiKey,
        api_secret: apiSecret,
    });

    cloudinary.v2.uploader.upload(file, {tags: 'test'}, function(error, image) {
        console.log("***FILE UPLOAD***");
        if (error) {
            console.warn(error);
        };
        console.log("*** public_id for the uploaded image is generated by Cloudinary's service ***");
        console.log("* " + image.public_id);
        console.log("* " + image.url);
        console.log(image);
    });
};

module.exports = router;
